name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout # set up your github account info and fetch your source code 
        uses: actions/checkout@v2
        
      - name: Install gtest
        run: sudo apt install libgtest-dev cmake

      - name: Build gtest
        working-directory: /usr/src/gtest
        run: | 
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/lib
        
      - name: Compile and Run
        run: |
          g++ -Wall -g -pthread *.cc -lgtest_main  -lgtest -lpthread -o main
          ./main
